---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cm

<!-- badges: start -->
<!-- badges: end -->

WIP on proof of concept (poc) for a contact matrix class that could underpin
various packages
(e.g. [socialmixr](https://cran.r-project.org/package=socialmixr)).

## Installation

You can install cm from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("TimTaylor/cm")
```

## Example

```{r}
library(tibble)
library(cm)

dat <- tribble(
        ~age,  ~gender,    ~age,  ~gender, ~value,
     "young",   "male",   "old", "female",     1L,
     "young", "female",   "old", "female",     2L,
       "old", "female", "young", "female",     2L
)

from <- .subset(dat, 1:2)
to <- .subset(dat, 3:4)
value <- .subset2(dat, 5L)

contact_matrix(from, to, value)

```
